name: Deploy static pages

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # EcoWheelz:
      - name: Build EcoWheelz
        working-directory: ./EcoWheelz
        run: |
          npm install
          npm run build
          rm -rf node_modules

      # ThrillRoll:
      - name: Build ThrillRoll
        working-directory: ./ThrillRoll
        run: |
          npm install
          npm run build
          rm -rf node_modules

      # SpeedyShed:
      - name: Build SpeedyShed
        working-directory: ./SpeedyShed
        run: |
          npm install
          npm run build
          rm -rf node_modules

      # UrbanGlide:
      - name: Build UrbanGlide
        working-directory: ./UrbanGlide
        run: |
          npm install
          npm run build
          rm -rf node_modules

      # Scootastic:
      - name: Build Scootastic
        working-directory: ./Scootastic
        run: |
          npm install
          npm run build
          rm -rf node_modules

      # WheelWiz:
      - name: Build WheelWiz
        working-directory: ./WheelWiz
        run: |
          npm install
          npm run build
          rm -rf node_modules

      # ScootSpectrum:
      - name: Build ScootSpectrum
        working-directory: ./ScootSpectrum
        run: |
          npm install
          npm run build
          rm -rf node_modules

      # TwistNThrive:
      - name: Build TwistNThrive
        working-directory: ./TwistNThrive
        run: |
          npm install
          npm run build
          rm -rf node_modules

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
